version: '3.8'

services:
  mysql-db:
    image: mysql:8.1
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d

  expense-service:
    build: ./expense-service
    ports:
      - "8080:8080"
    container_name: expense-service
    environment:
      DB_HOST: mysql-db
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    depends_on:
      - mysql-db
     
  user-service:
    build: ./user-service
    ports:
      - "5000:5000"
    container_name: user-service
    environment:
      DB_HOST: mysql-db
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    depends_on:
      - mysql-db
      - expense-service

  frontend:
    build:
      context: ./frontend-new
      dockerfile: Dockerfile
    ports:
      - "80:80"
    container_name: frontend
    depends_on:
      - user-service
      - expense-service

volumes:
  mysql_data:

